name: 构建Android APK (备用方案)

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 设置Python环境
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
        
    - name: 设置Android环境
      uses: android-actions/setup-android@v3
      with:
        api-level: 28
        ndk-version: 20.1.5948944
        
    - name: 安装Buildozer
      run: |
        python -m pip install --upgrade pip
        pip install buildozer==1.4.0 cython==0.29.33
        pip install kivy==2.1.0 requests
        
    - name: 构建APK
      run: |
        # 设置环境变量
        export ANDROID_HOME=$ANDROID_SDK_ROOT
        export JAVA_HOME=$JAVA_HOME_8_X64
        
        # 显示环境信息
        echo "Android SDK: $ANDROID_SDK_ROOT"
        echo "Java Home: $JAVA_HOME"
        echo "NDK: $ANDROID_NDK_ROOT"
        
        # 构建APK
        buildozer android debug
        
    - name: 上传APK文件
      uses: actions/upload-artifact@v4
      with:
        name: 图片资源嗅探工具-备用构建
        path: bin/*.apk
        retention-days: 30